/**
 * Default form fields for MOC 106 Form
 * Israeli Income Tax Form with comprehensive field set
 * Used when PDF field extraction fails or returns no fields
 */

import type { FormField } from '@/types/form.types';

export const DEFAULT_FORM_FIELDS: FormField[] = [
  // Personal Information
  {
    name: 'full_name',
    type: 'text',
    label: 'Full Name',
    required: true,
    placeholder: 'Enter your full name',
    maxLength: 100,
  },
  {
    name: 'id_number',
    type: 'text',
    label: 'ID Number',
    required: true,
    placeholder: 'Enter ID number',
    maxLength: 20,
  },
  {
    name: 'date_of_birth',
    type: 'date',
    label: 'Date of Birth',
    required: false,
  },
  {
    name: 'marital_status',
    type: 'text',
    label: 'Marital Status',
    required: false,
    placeholder: 'Single / Married / Divorced / Widowed',
    maxLength: 50,
  },
  {
    name: 'address',
    type: 'text',
    label: 'Address',
    required: false,
    placeholder: 'Street address',
    maxLength: 200,
  },
  {
    name: 'city',
    type: 'text',
    label: 'City',
    required: false,
    placeholder: 'City name',
    maxLength: 100,
  },
  {
    name: 'postal_code',
    type: 'text',
    label: 'Postal Code',
    required: false,
    placeholder: 'Postal code',
    maxLength: 20,
  },
  {
    name: 'phone',
    type: 'tel',
    label: 'Phone Number',
    required: false,
    placeholder: 'Telephone number',
    maxLength: 20,
  },
  {
    name: 'email',
    type: 'email',
    label: 'Email Address',
    required: false,
    placeholder: 'Email address',
    maxLength: 100,
  },

  // Income Information
  {
    name: 'salary_wages',
    type: 'text',
    label: 'Salary / Wages',
    required: false,
    placeholder: 'Annual salary',
    maxLength: 50,
  },
  {
    name: 'self_employment_income',
    type: 'text',
    label: 'Self-Employment Income',
    required: false,
    placeholder: 'Business income',
    maxLength: 50,
  },
  {
    name: 'interest_income',
    type: 'text',
    label: 'Interest Income',
    required: false,
    placeholder: 'Interest from savings/investments',
    maxLength: 50,
  },
  {
    name: 'dividend_income',
    type: 'text',
    label: 'Dividend Income',
    required: false,
    placeholder: 'Dividend earnings',
    maxLength: 50,
  },
  {
    name: 'rental_income',
    type: 'text',
    label: 'Rental Income',
    required: false,
    placeholder: 'Income from rental property',
    maxLength: 50,
  },
  {
    name: 'other_income',
    type: 'text',
    label: 'Other Income',
    required: false,
    placeholder: 'Specify other income sources',
    maxLength: 100,
  },
  {
    name: 'total_income',
    type: 'text',
    label: 'Total Income',
    required: false,
    placeholder: 'Total annual income',
    maxLength: 50,
  },

  // Deductions
  {
    name: 'professional_expenses',
    type: 'text',
    label: 'Professional Expenses',
    required: false,
    placeholder: 'Work-related expenses',
    maxLength: 50,
  },
  {
    name: 'charitable_donations',
    type: 'text',
    label: 'Charitable Donations',
    required: false,
    placeholder: 'Donation amount',
    maxLength: 50,
  },
  {
    name: 'mortgage_interest',
    type: 'text',
    label: 'Mortgage Interest',
    required: false,
    placeholder: 'Annual mortgage interest',
    maxLength: 50,
  },
  {
    name: 'medical_expenses',
    type: 'text',
    label: 'Medical Expenses',
    required: false,
    placeholder: 'Medical and healthcare costs',
    maxLength: 50,
  },
  {
    name: 'life_insurance_premiums',
    type: 'text',
    label: 'Life Insurance Premiums',
    required: false,
    placeholder: 'Annual insurance premiums',
    maxLength: 50,
  },
  {
    name: 'education_expenses',
    type: 'text',
    label: 'Education Expenses',
    required: false,
    placeholder: 'Tuition and education costs',
    maxLength: 50,
  },
  {
    name: 'child_support_alimony',
    type: 'text',
    label: 'Child Support / Alimony',
    required: false,
    placeholder: 'Support payments',
    maxLength: 50,
  },
  {
    name: 'total_deductions',
    type: 'text',
    label: 'Total Deductions',
    required: false,
    placeholder: 'Total deductions',
    maxLength: 50,
  },

  // Tax Information
  {
    name: 'taxable_income',
    type: 'text',
    label: 'Taxable Income',
    required: false,
    placeholder: 'Income subject to tax',
    maxLength: 50,
  },
  {
    name: 'income_tax_withheld',
    type: 'text',
    label: 'Income Tax Withheld',
    required: false,
    placeholder: 'Tax already withheld by employer',
    maxLength: 50,
  },
  {
    name: 'vat_paid',
    type: 'text',
    label: 'VAT Paid',
    required: false,
    placeholder: 'Value Added Tax paid',
    maxLength: 50,
  },
  {
    name: 'estimated_tax_payments',
    type: 'text',
    label: 'Estimated Tax Payments',
    required: false,
    placeholder: 'Quarterly estimated tax payments',
    maxLength: 50,
  },
  {
    name: 'total_tax_credits',
    type: 'text',
    label: 'Total Tax Credits',
    required: false,
    placeholder: 'Tax credits and adjustments',
    maxLength: 50,
  },
  {
    name: 'tax_due',
    type: 'text',
    label: 'Total Tax Due',
    required: false,
    placeholder: 'Amount of tax due or refund',
    maxLength: 50,
  },

  // Additional Information
  {
    name: 'statement_date',
    type: 'date',
    label: 'Statement Date',
    required: false,
  },
  {
    name: 'preparer_name',
    type: 'text',
    label: 'Preparer Name (if applicable)',
    required: false,
    placeholder: 'Name of tax preparer',
    maxLength: 100,
  },
  {
    name: 'preparer_signature',
    type: 'text',
    label: 'Preparer Signature',
    required: false,
    placeholder: 'Signature',
    maxLength: 100,
  },
  {
    name: 'taxpayer_signature',
    type: 'text',
    label: 'Taxpayer Signature',
    required: false,
    placeholder: 'Your signature',
    maxLength: 100,
  },
  {
    name: 'notes',
    type: 'textarea',
    label: 'Additional Notes',
    required: false,
    placeholder: 'Add any additional information',
    maxLength: 500,
  },
];
